### ISSUE TITLE
About using Moveit2 with z1 in ROS2

### ISSUE THREAD

**Issue by LebinLiang** [idra-lab/unitree_z1_hw_interface#9]
I am trying to control the Z1 robot using MoveIt2 in ROS2.  
While the basic controller setup seems to work fine, MoveIt is unable to send motion commands to the robot properly.

---

## Steps to Reproduce

1. Launch the robot with the controller:

   ```bash
   ros2 launch z1_bringup z1.launch.py starting_controller:=joint_trajectory_controller
   ```

   - The robot and the `joint_trajectory_controller` start successfully.

2. Configure MoveIt2 using the Setup Assistant:

   ```bash
   ros2 run moveit_setup_assistant moveit_setup_assistant
   ```

   - Based on the `z1_description` xacro files, I configured and exported the `z1_moveit` package.

3. Launch MoveIt2:

   ```bash
   ros2 launch z1_moveit demo.launch.py
   ```

---

## Expected Behavior

MoveIt2 should be able to send planned trajectories to the `joint_trajectory_controller`, and the robot should move accordingly.

---

## Actual Behavior

MoveIt2 launches successfully and RViz visualization is running.  
However, when I plan and execute a motion, the robot does not move.  
Meanwhile, the following errors appear in the console:

```plaintext
[rviz2-6] [INFO] [1745761087.370575116] [rviz]: Connected on namespace: /motion_control_handle
[ruby $(which ign) gazebo-4] [ERROR] [1745761101.814931226] [controller_manager]: The 'type' param was not defined for 'z1_controller'.
[ruby $(which ign) gazebo-4] [INFO] [1745761101.815749813] [controller_manager]: Configuring controller 'joint_state_broadcaster'
[ruby $(which ign) gazebo-4] [ERROR] [1745761101.815800994] [controller_manager]: Controller 'joint_state_broadcaster' can not be configured from 'active' state.
```

---

## moveit_controllers.yaml Configuration

```yaml
# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - z1_controller

  z1_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    default: true
```

---

## Environment

- **ROS2 Version**: [Humble]
- **Simulation/Hardware**: [Ignition Gazebo  / RViz2 / Real Robot]
- **Robot**: Z1

---

## Additional Information

- The `joint_trajectory_controller` starts without errors at the beginning.
- Motion planning in MoveIt completes successfully, but no actual motion is observed.
- The error messages suggest that the controller manager has trouble configuring the controllers properly, possibly due to a missing or incorrect `type` parameter for `z1_controller`.

---

## Questions

- Do I need to explicitly define the `type` for `z1_controller` somewhere else in the MoveIt or bringup configurations?
- Is there an issue with the MoveIt controller interface setup in my `moveit_controllers.yaml`?
- Should additional configuration be added to the `controller_manager` or launch files to properly bridge MoveIt2 and the controllers?

---

![Image](https://github.com/user-attachments/assets/4036d764-7d52-490e-ba35-3ea614414b27)
